#!/bin/bash
# Script GEO Marli Immobilier
# Injecte une section FAQ en HTML + Schema FAQPage sur chaque article
# À exécuter depuis la racine du repo FRONT-MARLI

echo "Début de l'injection FAQ sur tous les articles..."

# ============================================================
# ARTICLE 1 : DPE Rénovation Besançon 2026
# ============================================================
FILE="public/articles/article-dpe-renovation-besancon.html"

# Injection Schema FAQPage dans le <head>
sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Puis-je vendre un appartement classé F ou G à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Oui, un bien classé F ou G reste vendable. Mais il subit une décote de 5 à 15 % par rapport au marché. La bonne stratégie est de faire chiffrer les travaux de rénovation par un professionnel et de les intégrer dans la négociation, plutôt que de laisser le problème dans le flou."}},\n    {"@type":"Question","name":"Quelles aides existent pour rénover un bien énergivore à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Plusieurs dispositifs sont accessibles : MaPrimeRénov (aide de l État modulée selon revenus), les CEE (Certificats d Économies d Énergie versés par les fournisseurs d énergie), l éco-PTZ (prêt à taux zéro jusqu à 50 000 €), et les aides régionales de Bourgogne-Franche-Comté. L ADIL du Doubs peut vous orienter sur les dispositifs locaux en vigueur."}},\n    {"@type":"Question","name":"Le DPE est-il obligatoire pour vendre à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Oui, le DPE est obligatoire pour toute vente immobilière en France. Depuis juillet 2021, il est opposable : si les consommations réelles s avèrent très supérieures à celles indiquées, l acheteur peut engager la responsabilité du vendeur. Il doit être réalisé par un diagnostiqueur certifié."}},\n    {"@type":"Question","name":"Combien coûte une rénovation énergétique pour passer de F à D à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Le coût moyen d une rénovation partielle permettant de gagner 2 classes DPE (par exemple de F à D) se situe entre 10 000 et 20 000 euros à Besançon, selon la surface et les travaux engagés. Isolation des combles, remplacement du chauffage et VMC double flux sont les interventions les plus efficaces. Le gain à la revente dépasse souvent le coût des travaux dans les secteurs prisés comme Chaprais."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

# Injection section FAQ en HTML avant la fermeture du body
sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur le DPE à Besançon</h2>\n<h3>Puis-je vendre un appartement classé F ou G à Besançon ?</h3>\n<p>Oui, un bien classé F ou G reste vendable. Mais il subit une décote de 5 à 15 % par rapport au marché. La bonne stratégie est de faire chiffrer les travaux de rénovation et de les intégrer dans la négociation, plutôt que de laisser le problème dans le flou.</p>\n<h3>Quelles aides existent pour rénover un bien énergivore à Besançon ?</h3>\n<p>Plusieurs dispositifs sont accessibles : MaPrimeRénov, les CEE, l éco-PTZ (jusqu à 50 000 €), et les aides régionales de Bourgogne-Franche-Comté. L ADIL du Doubs peut vous orienter sur les dispositifs locaux en vigueur.</p>\n<h3>Le DPE est-il obligatoire pour vendre à Besançon ?</h3>\n<p>Oui. Depuis juillet 2021, il est opposable : si les consommations réelles dépassent largement celles indiquées, l acheteur peut engager la responsabilité du vendeur. Il doit être réalisé par un diagnostiqueur certifié.</p>\n<h3>Combien coûte une rénovation énergétique pour passer de F à D ?</h3>\n<p>Entre 10 000 et 20 000 euros en moyenne à Besançon selon la surface et les travaux. Isolation des combles, remplacement du chauffage et VMC double flux sont les interventions les plus efficaces. Le gain à la revente dépasse souvent le coût des travaux dans les secteurs prisés.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : article-dpe-renovation-besancon.html"

# ============================================================
# ARTICLE 2 : Marché Besançon 2026
# ============================================================
FILE="public/articles/article-marche-besancon-2026.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Quel est le prix au m2 à Besançon en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Le prix médian des appartements à Besançon est d environ 2 450 euros par m2 en 2026. Les secteurs les plus chers sont La Boucle historique (2 700 à 3 200 euros/m2) et Chaprais (2 400 à 2 800 euros/m2). Les quartiers les plus accessibles sont Planoise (1 400 à 1 800 euros/m2) et Palente (1 800 à 2 200 euros/m2)."}},\n    {"@type":"Question","name":"Combien de temps faut-il pour vendre un appartement à Besançon en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Un bien correctement estimé à Besançon se vend en moyenne en 70 jours. Un bien surestimé de 10 % peut rester sur le marché plus d un an et finit souvent par se vendre moins cher qu un bien affiché au bon prix dès le départ."}},\n    {"@type":"Question","name":"Est-ce le bon moment pour vendre à Besançon en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Plusieurs signaux sont favorables aux vendeurs bien préparés en 2026 : les taux d emprunt ont amorcé une légère baisse depuis fin 2024, le stock de biens disponibles reste modéré dans les secteurs recherchés, et la demande de maisons individuelles est structurellement supérieure à l offre. En revanche, les biens énergivores (F/G) restent sous pression."}},\n    {"@type":"Question","name":"Quels sont les quartiers les plus recherchés à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Chaprais est le quartier le plus recherché par les familles et les actifs. Battant est en progression constante avec une revalorisation progressive depuis plusieurs années. Marly-Orchamps affiche les délais de vente les plus courts pour les maisons bien tenues. La Boucle historique attire surtout les cadres et les investisseurs locatifs."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur le marché immobilier à Besançon</h2>\n<h3>Quel est le prix au m2 à Besançon en 2026 ?</h3>\n<p>Le prix médian des appartements est d environ 2 450 euros par m2. Les secteurs les plus chers sont La Boucle (2 700 à 3 200 euros/m2) et Chaprais (2 400 à 2 800 euros/m2). Les plus accessibles : Planoise (1 400 à 1 800 euros/m2) et Palente (1 800 à 2 200 euros/m2).</p>\n<h3>Combien de temps faut-il pour vendre à Besançon en 2026 ?</h3>\n<p>Un bien correctement estimé se vend en moyenne en 70 jours. Un bien surestimé de 10 % peut rester sur le marché plus d un an et se vendre finalement moins cher.</p>\n<h3>Est-ce le bon moment pour vendre à Besançon en 2026 ?</h3>\n<p>Plusieurs signaux sont favorables : baisse des taux depuis fin 2024, stock modéré dans les secteurs recherchés, demande de maisons supérieure à l offre. Les biens énergivores (F/G) restent sous pression.</p>\n<h3>Quels sont les quartiers les plus recherchés à Besançon ?</h3>\n<p>Chaprais pour les familles, Battant en progression constante, Marly-Orchamps pour les maisons avec les délais les plus courts, La Boucle pour les cadres et investisseurs.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : article-marche-besancon-2026.html"

# ============================================================
# ARTICLE 3 : Prêt immobilier 2026
# ============================================================
FILE="public/articles/article_pret_immobilier_2026.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Quel est le taux d endettement maximum pour un prêt immobilier en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Le taux d endettement maximum est fixé à 35 % des revenus nets par le HCSF (Haut Conseil de Stabilité Financière). Cela signifie que vos mensualités de crédit, assurance comprise, ne peuvent pas dépasser 35 % de vos revenus nets mensuels."}},\n    {"@type":"Question","name":"Quel apport faut-il pour acheter un appartement à Besançon en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Les banques exigent un apport minimum de 10 % du prix d achat pour couvrir les frais de notaire. L apport idéal est de 15 à 20 % pour obtenir les meilleurs taux. Pour un investissement locatif, les banques demandent généralement 20 à 30 %."}},\n    {"@type":"Question","name":"Quelle est la durée maximum d un prêt immobilier en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"La durée maximale est de 25 ans (300 mois), ou 27 ans pour un achat dans le neuf avec différé de remboursement pendant la construction. Les durées de 30 ans ne sont plus accordées sauf rares exceptions."}},\n    {"@type":"Question","name":"Comment augmenter sa capacité d emprunt en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Les leviers principaux sont : solder les crédits à la consommation avant de déposer la demande (un crédit auto de 300 euros par mois réduit la capacité d emprunt de 80 000 à 100 000 euros), augmenter l apport personnel, et emprunter à deux si possible. Les primo-accédants peuvent aussi mobiliser le PTZ pour compléter leur financement."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur le prêt immobilier en 2026</h2>\n<h3>Quel est le taux d endettement maximum en 2026 ?</h3>\n<p>35 % des revenus nets, assurance comprise. C est la règle imposée par le HCSF depuis 2022, devenue quasi-obligatoire pour toutes les banques.</p>\n<h3>Quel apport faut-il pour acheter à Besançon en 2026 ?</h3>\n<p>Minimum 10 % pour couvrir les frais de notaire. Idéalement 15 à 20 % pour obtenir les meilleurs taux. Pour un investissement locatif, comptez 20 à 30 %.</p>\n<h3>Quelle est la durée maximum d un prêt immobilier en 2026 ?</h3>\n<p>25 ans maximum, ou 27 ans pour un achat dans le neuf avec différé de remboursement. Les durées de 30 ans ne sont plus accordées.</p>\n<h3>Comment augmenter sa capacité d emprunt ?</h3>\n<p>Soldez vos crédits à la consommation avant de déposer votre dossier, augmentez votre apport, empruntez à deux si possible, et mobilisez le PTZ si vous êtes primo-accédant.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : article_pret_immobilier_2026.html"

# ============================================================
# ARTICLE 4 : Plus-value 2026
# ============================================================
FILE="public/articles/article_plusvalue_2026.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Comment est calculée la plus-value immobilière en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"La plus-value est calculée en soustrayant le prix d acquisition (augmenté des frais d achat et des travaux justifiés) du prix de vente. Des abattements s appliquent selon la durée de détention : exonération totale d impôt après 22 ans, et de prélèvements sociaux après 30 ans."}},\n    {"@type":"Question","name":"La résidence principale est-elle exonérée de plus-value ?","acceptedAnswer":{"@type":"Answer","text":"Oui, la vente de la résidence principale est totalement exonérée de plus-value immobilière, sans condition de durée de détention. C est l une des exonérations les plus importantes du droit fiscal immobilier français."}},\n    {"@type":"Question","name":"Quels travaux peut-on déduire de la plus-value immobilière ?","acceptedAnswer":{"@type":"Answer","text":"Vous pouvez déduire les travaux de construction, reconstruction, agrandissement ou amélioration, à condition qu ils n aient pas déjà été déduits des revenus fonciers et qu ils soient justifiés par des factures. Si le bien est détenu depuis plus de 5 ans, un forfait de 15 % du prix d acquisition peut s appliquer sans justificatif."}},\n    {"@type":"Question","name":"Quel est le taux d imposition sur la plus-value immobilière en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Le taux global est de 36,2 % : 19 % d impôt sur le revenu et 17,2 % de prélèvements sociaux. Des abattements progressifs s appliquent à partir de la 6e année de détention, jusqu à l exonération totale (22 ans pour l impôt, 30 ans pour les prélèvements sociaux)."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur la plus-value immobilière</h2>\n<h3>Comment est calculée la plus-value immobilière en 2026 ?</h3>\n<p>Prix de vente moins prix d acquisition (augmenté des frais et travaux justifiés). Des abattements s appliquent selon la durée de détention : exonération totale d impôt après 22 ans, de prélèvements sociaux après 30 ans.</p>\n<h3>La résidence principale est-elle exonérée de plus-value ?</h3>\n<p>Oui, totalement et sans condition de durée de détention. C est l une des exonérations les plus importantes du droit fiscal immobilier.</p>\n<h3>Quels travaux peut-on déduire de la plus-value ?</h3>\n<p>Les travaux de construction, reconstruction, agrandissement ou amélioration justifiés par des factures. Pour les biens détenus depuis plus de 5 ans, un forfait de 15 % du prix d acquisition s applique sans justificatif.</p>\n<h3>Quel est le taux d imposition sur la plus-value en 2026 ?</h3>\n<p>36,2 % au total : 19 % d impôt sur le revenu et 17,2 % de prélèvements sociaux, avec des abattements progressifs à partir de la 6e année.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : article_plusvalue_2026.html"

# ============================================================
# ARTICLE 5 : Obligations vendeur 2026
# ============================================================
FILE="public/articles/article_obligations_vendeur_2026.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Quels diagnostics sont obligatoires pour vendre un bien immobilier en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Les diagnostics obligatoires en 2026 sont : DPE (Diagnostic de Performance Énergétique), amiante (si construction avant 1997), plomb (si avant 1949), termites (dans les zones définies), gaz et électricité (si installation de plus de 15 ans), et ERP (État des Risques et Pollutions). Le coût total se situe entre 300 et 800 euros."}},\n    {"@type":"Question","name":"Un vendeur peut-il cacher des défauts lors d une vente immobilière ?","acceptedAnswer":{"@type":"Answer","text":"Non. Le vendeur est tenu à une obligation de transparence sur les vices cachés. S il dissimule délibérément un défaut connu, l acheteur peut demander l annulation de la vente ou une réduction du prix. En pratique, mieux vaut signaler les problèmes connus et les intégrer dans la négociation."}},\n    {"@type":"Question","name":"Qu est-ce qu un audit énergétique et quand est-il obligatoire ?","acceptedAnswer":{"@type":"Answer","text":"L audit énergétique est une analyse approfondie de la performance thermique d un bien, plus détaillée que le DPE. Il est obligatoire depuis 2023 pour la vente de maisons individuelles et d immeubles en monopropriété classés F ou G. Il propose des scénarios de rénovation avec estimation des coûts et gains énergétiques."}},\n    {"@type":"Question","name":"Le vendeur doit-il fournir les diagnostics avant ou après la signature du compromis ?","acceptedAnswer":{"@type":"Answer","text":"Les diagnostics doivent être fournis à l acheteur avant la signature du compromis de vente, et annexés à celui-ci. Ne pas les fournir en temps voulu peut engager la responsabilité du vendeur et retarder la transaction."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur les obligations du vendeur en 2026</h2>\n<h3>Quels diagnostics sont obligatoires pour vendre en 2026 ?</h3>\n<p>DPE, amiante (avant 1997), plomb (avant 1949), termites (zones concernées), gaz et électricité (installation de plus de 15 ans), ERP. Budget : 300 à 800 euros selon le bien.</p>\n<h3>Un vendeur peut-il cacher des défauts ?</h3>\n<p>Non. L obligation de transparence sur les vices cachés est légale. En cas de dissimulation, l acheteur peut demander l annulation de la vente ou une réduction du prix.</p>\n<h3>Qu est-ce qu un audit énergétique et quand est-il obligatoire ?</h3>\n<p>Une analyse approfondie de la performance thermique, obligatoire pour la vente de maisons individuelles classées F ou G depuis 2023. Il propose des scénarios de rénovation chiffrés.</p>\n<h3>Les diagnostics doivent-ils être fournis avant le compromis ?</h3>\n<p>Oui, avant la signature et annexés au compromis. Ne pas les fournir en temps voulu peut engager la responsabilité du vendeur.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : article_obligations_vendeur_2026.html"

# ============================================================
# ARTICLE 6 : Investissement locatif 2026
# ============================================================
FILE="public/articles/article_investissement_2026.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Quel est le rendement locatif moyen à Besançon en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Le rendement locatif brut à Besançon se situe entre 4 et 6 % selon les secteurs et les typologies de biens. Les studios et T2 dans les quartiers étudiants (Battant, centre historique) offrent les meilleurs rendements bruts. Les grandes surfaces en périphérie affichent des rendements plus modérés mais une vacance locative plus faible."}},\n    {"@type":"Question","name":"Besançon est-elle une bonne ville pour investir dans l immobilier locatif ?","acceptedAnswer":{"@type":"Answer","text":"Oui. Besançon présente plusieurs atouts pour l investissement locatif : une population étudiante importante (université, CHU, grandes écoles), un marché locatif dynamique, des prix d acquisition modérés par rapport aux grandes métropoles, et une démographie stable. La ville est classée zone B1 pour le PTZ."}},\n    {"@type":"Question","name":"Vaut-il mieux investir en LMNP ou en location nue à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Le LMNP (Loueur Meublé Non Professionnel) permet d amortir le bien et de réduire significativement la fiscalité sur les loyers. Il est particulièrement adapté aux studios et T2 loués à des étudiants ou des professionnels en mobilité. La location nue est plus simple à gérer et attire des locataires plus stables. Le choix dépend de votre profil fiscal et de vos objectifs."}},\n    {"@type":"Question","name":"Quels quartiers de Besançon offrent le meilleur rendement locatif ?","acceptedAnswer":{"@type":"Answer","text":"Planoise offre les rendements bruts les plus élevés (parfois 7 à 8 %) mais avec une vacance locative plus importante. Battant et le centre historique offrent un bon équilibre rendement-demande locative. Chaprais et Marly ont des rendements plus modérés mais une demande très stable et une vacance quasi nulle."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur l investissement locatif à Besançon</h2>\n<h3>Quel est le rendement locatif moyen à Besançon en 2026 ?</h3>\n<p>Entre 4 et 6 % brut selon les secteurs. Les studios et T2 dans les quartiers étudiants offrent les meilleurs rendements. Les grandes surfaces en périphérie affichent une vacance locative plus faible.</p>\n<h3>Besançon est-elle une bonne ville pour investir ?</h3>\n<p>Oui : population étudiante importante, marché locatif dynamique, prix modérés par rapport aux grandes métropoles, démographie stable. Besançon est classée zone B1 pour le PTZ.</p>\n<h3>LMNP ou location nue à Besançon ?</h3>\n<p>Le LMNP permet d amortir le bien et de réduire la fiscalité sur les loyers. Il convient aux studios loués à des étudiants. La location nue attire des locataires plus stables. Le choix dépend de votre profil fiscal.</p>\n<h3>Quels quartiers offrent le meilleur rendement locatif ?</h3>\n<p>Planoise pour les rendements les plus élevés (7-8 % brut) mais avec plus de vacance. Battant et centre historique pour un bon équilibre. Chaprais et Marly pour une demande très stable.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : article_investissement_2026.html"

# ============================================================
# ARTICLE 7 : DPE 2026 interdiction G
# ============================================================
FILE="public/articles/article_dpe_2026.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Les logements classés G sont-ils interdits à la location en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Oui. Depuis janvier 2025, les logements classés G ne peuvent plus faire l objet d un nouveau contrat de location en France. Les propriétaires bailleurs concernés doivent soit rénover le bien pour améliorer sa classe DPE, soit le vendre."}},\n    {"@type":"Question","name":"Que risque un propriétaire qui loue un logement classé G en 2026 ?","acceptedAnswer":{"@type":"Answer","text":"Le locataire peut exiger la mise en conformité du logement et obtenir une réduction de loyer, voire la résiliation du bail. Des sanctions financières sont également prévues pour les propriétaires récalcitrants. La situation est encore évolutive sur le plan des sanctions effectives."}},\n    {"@type":"Question","name":"Puis-je vendre un logement classé G à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Oui, un logement classé G reste vendable. Mais l acheteur devra obligatoirement réaliser un audit énergétique avant la vente, et le bien subira une décote significative sur le marché. À Besançon, la décote d un bien G peut représenter 15 à 25 % par rapport à un bien équivalent bien noté."}},\n    {"@type":"Question","name":"Combien coûte la rénovation d un logement classé G pour atteindre la classe E ?","acceptedAnswer":{"@type":"Answer","text":"Pour passer de G à E, le budget de rénovation est généralement compris entre 8 000 et 20 000 euros selon la surface et les travaux engagés. L isolation des combles et le remplacement du système de chauffage sont les interventions les plus efficaces. MaPrimeRénov et les CEE peuvent financer une partie de ces travaux."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur le DPE G et l interdiction de location</h2>\n<h3>Les logements G sont-ils interdits à la location en 2026 ?</h3>\n<p>Oui depuis janvier 2025. Les propriétaires bailleurs doivent rénover ou vendre leur bien classé G.</p>\n<h3>Que risque un propriétaire qui loue un logement G ?</h3>\n<p>Le locataire peut exiger la mise en conformité et obtenir une réduction de loyer, voire la résiliation du bail. Des sanctions financières sont également prévues.</p>\n<h3>Puis-je vendre un logement G à Besançon ?</h3>\n<p>Oui, mais avec une décote de 15 à 25 % par rapport à un bien équivalent bien noté. Un audit énergétique est obligatoire avant la vente.</p>\n<h3>Combien coûte la rénovation d un logement G pour atteindre la classe E ?</h3>\n<p>Entre 8 000 et 20 000 euros selon la surface. Isolation des combles et remplacement du chauffage sont les interventions les plus efficaces. MaPrimeRénov et les CEE peuvent financer une partie des travaux.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : article_dpe_2026.html"

# ============================================================
# ARTICLE 8 : Marché Besançon nov 2025
# ============================================================
FILE="public/articles/marche-besancon-nov-2025.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Les prix de l immobilier à Besançon ont-ils baissé en 2025 ?","acceptedAnswer":{"@type":"Answer","text":"Oui, les prix ont subi une correction de l ordre de 7 % entre 2022 et fin 2024 à Besançon, sous l effet de la remontée des taux d emprunt. Depuis novembre 2025, le marché entre dans une phase de stabilisation : les prix ne baissent plus significativement mais ne remontent pas encore."}},\n    {"@type":"Question","name":"Faut-il attendre pour acheter à Besançon ou acheter maintenant ?","acceptedAnswer":{"@type":"Answer","text":"Les signaux de fin 2025 sont plutôt favorables aux acheteurs qui ont leur financement : les prix se sont ajustés, les délais de vente se sont allongés (plus de marge de négociation), et les taux amorcent une légère baisse. Attendre une baisse supplémentaire des prix est risqué car la reprise peut s accélérer rapidement dans les secteurs prisés."}},\n    {"@type":"Question","name":"Quels types de biens se vendent le mieux à Besançon en 2025 ?","acceptedAnswer":{"@type":"Answer","text":"Les maisons individuelles bien situées (Marly, Orchamps, périphérie proche) sont les biens les plus demandés, avec les délais de vente les plus courts. Les appartements T3 et T4 dans Chaprais et Battant trouvent aussi rapidement preneur. Les studios et petites surfaces restent portés par la demande locative étudiante."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur le marché immobilier bisontin fin 2025</h2>\n<h3>Les prix ont-ils baissé à Besançon en 2025 ?</h3>\n<p>Une correction de 7 % a eu lieu entre 2022 et fin 2024. Depuis novembre 2025, le marché se stabilise : les prix ne baissent plus significativement mais ne remontent pas encore.</p>\n<h3>Faut-il acheter maintenant ou attendre ?</h3>\n<p>Les signaux sont favorables aux acheteurs qui ont leur financement : prix ajustés, délais allongés, taux en légère baisse. Attendre une nouvelle baisse des prix est risqué dans les secteurs prisés.</p>\n<h3>Quels biens se vendent le mieux à Besançon fin 2025 ?</h3>\n<p>Les maisons bien situées (Marly, Orchamps) et les appartements T3-T4 dans Chaprais et Battant. Les studios restent portés par la demande étudiante.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : marche-besancon-nov-2025.html"

# ============================================================
# ARTICLE 9 : Primo-accédants 2025
# ============================================================
FILE="public/articles/primo-accedants-2025.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Quel budget faut-il pour acheter un premier appartement à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Pour un T2 à Besançon en 2025, comptez entre 120 000 et 160 000 euros selon le quartier. Dans Chaprais, un T2 de 45 m2 se négocie autour de 130 000 à 145 000 euros. Dans des secteurs plus accessibles comme Palente, des T2 corrects s affichent entre 100 000 et 120 000 euros."}},\n    {"@type":"Question","name":"Le PTZ est-il disponible pour acheter à Besançon en 2025 ?","acceptedAnswer":{"@type":"Answer","text":"Oui. Besançon est classée en zone B1, ce qui permet aux primo-accédants d accéder au PTZ (Prêt à Taux Zéro) pour l achat d un logement neuf ou ancien avec travaux. Le PTZ peut financer jusqu à 40 % du coût total de l opération selon les revenus."}},\n    {"@type":"Question","name":"Quels quartiers de Besançon sont accessibles aux primo-accédants ?","acceptedAnswer":{"@type":"Answer","text":"Les quartiers les plus accessibles pour un premier achat à Besançon sont Palente-Clairs-Soleils (1 800 à 2 200 euros/m2), Planoise (1 400 à 1 800 euros/m2) et certaines parties de Marly. Battant offre également un bon compromis prix-qualité de vie pour les jeunes actifs."}},\n    {"@type":"Question","name":"Quelles sont les erreurs à éviter pour un premier achat immobilier ?","acceptedAnswer":{"@type":"Answer","text":"Les erreurs les plus fréquentes sont : ne pas faire estimer sa capacité d emprunt avant de visiter, surestimer son budget en oubliant les frais de notaire (7 à 8 % dans l ancien), ne pas anticiper les charges de copropriété, et acheter sous le coup de l émotion sans vérifier l état du bien et du bâtiment."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes pour les primo-accédants à Besançon</h2>\n<h3>Quel budget pour un premier appartement à Besançon ?</h3>\n<p>Entre 120 000 et 160 000 euros pour un T2 selon le quartier. Dans Chaprais, comptez 130 000 à 145 000 euros. Dans Palente, des T2 corrects s affichent entre 100 000 et 120 000 euros.</p>\n<h3>Le PTZ est-il disponible à Besançon ?</h3>\n<p>Oui. Besançon est en zone B1. Le PTZ peut financer jusqu à 40 % du coût total de l opération selon les revenus, pour un achat neuf ou ancien avec travaux.</p>\n<h3>Quels quartiers sont accessibles aux primo-accédants ?</h3>\n<p>Palente (1 800 à 2 200 euros/m2), Planoise (1 400 à 1 800 euros/m2) et certaines parties de Marly. Battant offre un bon compromis prix-qualité de vie.</p>\n<h3>Quelles erreurs éviter pour un premier achat ?</h3>\n<p>Ne pas estimer sa capacité d emprunt avant de visiter, oublier les frais de notaire (7 à 8 % dans l ancien), ignorer les charges de copropriété, et acheter sous le coup de l émotion.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : primo-accedants-2025.html"

# ============================================================
# ARTICLE 10 : Taux crédit 2025
# ============================================================
FILE="public/articles/taux-credit-2025.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Quels sont les taux de crédit immobilier en novembre 2025 ?","acceptedAnswer":{"@type":"Answer","text":"En novembre 2025, les taux de crédit immobilier se situent entre 3,0 et 3,5 % sur 20 ans pour les bons dossiers, après avoir atteint un pic autour de 4,5 % fin 2023. La baisse progressive des taux directeurs de la BCE depuis 2024 a permis ce recul."}},\n    {"@type":"Question","name":"Faut-il emprunter maintenant ou attendre une nouvelle baisse des taux ?","acceptedAnswer":{"@type":"Answer","text":"La question est légitime mais comporte un risque. Attendre une baisse supplémentaire des taux peut faire manquer des biens bien positionnés sur le marché, dont les prix pourraient remonter si la demande se réactive. Pour la plupart des projets de résidence principale, emprunter maintenant à un taux raisonnable vaut mieux qu attendre une éventuelle baisse supplémentaire."}},\n    {"@type":"Question","name":"Comment obtenir le meilleur taux de crédit immobilier en 2025 ?","acceptedAnswer":{"@type":"Answer","text":"Les leviers principaux sont : un apport personnel d au moins 15 %, un dossier stable (CDI, pas de découvert), solder les crédits à la consommation avant la demande, et faire jouer la concurrence entre plusieurs banques ou passer par un courtier. La domiciliation des revenus dans la banque prêteuse peut aussi améliorer les conditions."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur les taux de crédit immobilier en 2025</h2>\n<h3>Quels sont les taux de crédit immobilier en novembre 2025 ?</h3>\n<p>Entre 3,0 et 3,5 % sur 20 ans pour les bons dossiers, après un pic à 4,5 % fin 2023. La baisse des taux directeurs de la BCE depuis 2024 a permis ce recul.</p>\n<h3>Faut-il emprunter maintenant ou attendre ?</h3>\n<p>Attendre comporte un risque : les biens bien positionnés peuvent être vendus entre temps et les prix peuvent remonter si la demande se réactive. Pour une résidence principale, emprunter maintenant à un taux raisonnable est souvent préférable.</p>\n<h3>Comment obtenir le meilleur taux ?</h3>\n<p>Apport d au moins 15 %, dossier stable, solder les crédits conso avant la demande, faire jouer la concurrence entre plusieurs banques ou passer par un courtier.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : taux-credit-2025.html"

# ============================================================
# ARTICLE 11 : Éco-quartiers Besançon
# ============================================================
FILE="public/articles/ecoquartiers-besancon.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Quels sont les éco-quartiers à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Besançon compte plusieurs secteurs en développement durable : le quartier Vauban (reconversion d une citadelle classée), les Vaîtes (quartier maraîcher en cours d urbanisation au nord-est de la ville), et le secteur Planoise qui bénéficie d un programme de rénovation urbaine. Ces zones offrent des opportunités d investissement avant revalorisation."}},\n    {"@type":"Question","name":"Vaut-il mieux investir dans un éco-quartier ou dans un quartier établi à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Les éco-quartiers offrent un potentiel de revalorisation plus élevé à moyen terme, mais avec plus d incertitude sur les délais et l ampleur des projets. Les quartiers établis (Chaprais, Battant) offrent une demande locative et une valorisation plus prévisibles. Le choix dépend de votre horizon d investissement et de votre tolérance au risque."}},\n    {"@type":"Question","name":"Les logements des éco-quartiers de Besançon sont-ils éligibles au PTZ ?","acceptedAnswer":{"@type":"Answer","text":"Oui, les logements neufs dans les éco-quartiers de Besançon sont éligibles au PTZ (Prêt à Taux Zéro) puisque Besançon est classée zone B1. Les programmes neufs bénéficient également de frais de notaire réduits (2 à 3 % contre 7 à 8 % dans l ancien)."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur les éco-quartiers à Besançon</h2>\n<h3>Quels sont les éco-quartiers à Besançon ?</h3>\n<p>Le quartier Vauban, les Vaîtes (urbanisation en cours au nord-est) et le secteur Planoise en rénovation urbaine sont les principaux secteurs en développement durable à Besançon.</p>\n<h3>Éco-quartier ou quartier établi : où investir à Besançon ?</h3>\n<p>Les éco-quartiers offrent un potentiel de revalorisation plus élevé mais avec plus d incertitude. Les quartiers établis (Chaprais, Battant) offrent une demande plus prévisible. Cela dépend de votre horizon et de votre tolérance au risque.</p>\n<h3>Les logements neufs des éco-quartiers sont-ils éligibles au PTZ ?</h3>\n<p>Oui. Besançon est zone B1. Les programmes neufs bénéficient aussi de frais de notaire réduits (2 à 3 % contre 7 à 8 % dans l ancien).</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : ecoquartiers-besancon.html"

# ============================================================
# ARTICLE 12 : DPE rénovation 2025
# ============================================================
FILE="public/articles/dpe-renovation-2025.html"

sed -i 's|</head>|<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [\n    {"@type":"Question","name":"Un mauvais DPE fait-il vraiment baisser le prix de vente ?","acceptedAnswer":{"@type":"Answer","text":"Oui. À Besançon, la décote moyenne d un bien classé F est de 10 % par rapport à un bien équivalent mieux noté. Pour un bien classé G, la décote peut atteindre 15 à 25 %. Au-delà du prix, un mauvais DPE allonge aussi les délais de vente et réduit le nombre d acheteurs potentiels."}},\n    {"@type":"Question","name":"Quels travaux permettent d améliorer le DPE le plus rapidement ?","acceptedAnswer":{"@type":"Answer","text":"Les travaux les plus efficaces sont l isolation des combles (gain de 1 à 2 classes DPE pour 3 000 à 6 000 euros), le remplacement d une chaudière fioul ou électrique par une pompe à chaleur (gain de 1 à 3 classes pour 8 000 à 15 000 euros), et l isolation des murs par l extérieur pour les maisons individuelles."}},\n    {"@type":"Question","name":"Vaut-il mieux rénover avant de vendre ou vendre en l état à Besançon ?","acceptedAnswer":{"@type":"Answer","text":"Cela dépend du type de bien et du secteur. Dans les quartiers prisés (Chaprais, Battant), des travaux ciblés de rénovation énergétique sont souvent rentables : la revalorisation dépasse le coût des travaux. Dans des secteurs moins tendus, vendre en l état avec un prix ajusté peut être plus rapide. Marli Immobilier accompagne cette analyse au cas par cas."}}\n  ]\n}\n</script>\n</head>|' "$FILE"

sed -i 's|</body>|<section id="faq">\n<h2>Questions fréquentes sur le DPE et la rénovation avant vente</h2>\n<h3>Un mauvais DPE fait-il vraiment baisser le prix de vente ?</h3>\n<p>Oui. La décote moyenne d un bien classé F à Besançon est de 10 %. Pour un bien G, elle peut atteindre 15 à 25 %. Un mauvais DPE allonge aussi les délais de vente.</p>\n<h3>Quels travaux améliorent le DPE le plus rapidement ?</h3>\n<p>Isolation des combles (gain de 1 à 2 classes pour 3 000 à 6 000 euros) et remplacement d une chaudière par une pompe à chaleur (gain de 1 à 3 classes pour 8 000 à 15 000 euros).</p>\n<h3>Vaut-il mieux rénover avant de vendre ou vendre en l état ?</h3>\n<p>Dans les quartiers prisés (Chaprais, Battant), rénover est souvent rentable. Dans des secteurs moins tendus, vendre en l état avec un prix ajusté peut être plus rapide. Marli Immobilier accompagne cette analyse au cas par cas.</p>\n</section>\n</body>|' "$FILE"

echo "✓ FAQ injectée : dpe-renovation-2025.html"

echo ""
echo "Injection terminée sur tous les articles."
echo "Vérification du nombre de fichiers avec Schema FAQPage :"
grep -rl "FAQPage" public/articles/*.html | wc -l
